[build]
  command = "yarn run build"
  publish = "dist/frontend"
  functions = "dist/serverless"
  [build.environment]
    NODE_VERSION = "16.13.2"
    NPM_VERSION = "8.4.0"
    YARN_VERSION = "1.22.15"
