[build]
  command = "yarn run build"
  publish = "dist/frontend"
  functions = "dist/serverless"
  [build.environment]
    NODE_VERSION = "14.5.0"
    NPM_VERSION = "6.14.5"
    YARN_VERSION = "1.22.4"
